In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "order_id": [1,2,3,4,5,6,7,8],
    "category": ["Electronics","Clothing","Electronics","Food",
                 "Food","Clothing","Electronics","Food"],
    "amount": [500,100,300,50,80,150,400,60]
})
df

   order_id     category  amount
0         1  Electronics     500
1         2     Clothing     100
2         3  Electronics     300
3         4         Food      50
4         5         Food      80
5         6     Clothing     150
6         7  Electronics     400
7         8         Food      60

In [3]:
# Group by category.
# Calculate:
# Total sales amount.
# Average order amount.
# Maximum order amount.
# Number of orders.
# Reset the index.

df2 = df.groupby("category").agg({
    "amount" : ["sum", "mean", "max", "count"]
})
df2

            amount
               sum        mean  max count
category
Clothing       250  125.000000  150     2
Electronics   1200  400.000000  500     3
Food           190   63.333333   80     3

In [6]:
df2.columns = [
    "Total Sales",
    "Average Order",
    "Maximum Order",
    "Number of Orders"
]
df2

             Total Sales  Average Order  Maximum Order  Number of Orders
category
Clothing             250     125.000000            150                 2
Electronics         1200     400.000000            500                 3
Food                 190      63.333333             80                 3

In [7]:
# Sort by total sales descending
df2.sort_values("Total Sales", ascending=False)

             Total Sales  Average Order  Maximum Order  Number of Orders
category
Electronics         1200     400.000000            500                 3
Clothing             250     125.000000            150                 2
Food                 190      63.333333             80                 3

In [8]:
# save to excel file
df2.to_excel("category_sales_summary.xlsx")