In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "product": ["Laptop", "Phone", "Laptop", "Tablet", "Phone", "Tablet"],
    "sales": [5, 10, 3, 4, 7, 6],
    "revenue": [5000, 7000, 3000, 2000, 4900, 3000]
})
df

  product  sales  revenue
0  Laptop      5     5000
1   Phone     10     7000
2  Laptop      3     3000
3  Tablet      4     2000
4   Phone      7     4900
5  Tablet      6     3000

In [3]:
# group by product and calculate total sales and revenue and average revenue
df = df.groupby("product").agg(
    total_sales = ("sales", "sum"),
    total_revenue = ("revenue", "sum"),
    avg_revenue = ("revenue", "mean")
)
df

         total_sales  total_revenue  avg_revenue
product
Laptop             8           8000       4000.0
Phone             17          11900       5950.0
Tablet            10           5000       2500.0

In [7]:
# short by revenue (highest first)
df.sort_values("total_revenue", ascending=False)

         total_sales  total_revenue  avg_revenue
product
Phone             17          11900       5950.0
Laptop             8           8000       4000.0
Tablet            10           5000       2500.0

In [8]:
# save to csv file
df.to_csv("product_sales_report.csv")