In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [7]:
df2 = df.copy()
new_col_order = [col for col in df2.columns if col != "id"] + ["id"]
df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [12]:
df3 = pd.read_csv("employees.csv")
df3

   employee_id   name department  age  salary  experience  performance_score
0          101  Aarav         IT   24   50000           2                3.5
1          102   Sita         HR   29   60000           5                4.2
2          103    Ram    Finance   35   75000          10                3.8
3          104   Gita         IT   26   52000           3                4.0
4          105  Binod         HR   31   58000           6                3.2
5          106  Kiran    Finance   40   90000          15                4.5
6          107  Nisha         IT   23   48000           1                3.9
7          108  Sunil    Finance   38   85000          12                4.1

In [13]:
# renaming col names
df3.rename(columns={"employee_id":"id", "performance_score":"rating"})

    id   name department  age  salary  experience  rating
0  101  Aarav         IT   24   50000           2     3.5
1  102   Sita         HR   29   60000           5     4.2
2  103    Ram    Finance   35   75000          10     3.8
3  104   Gita         IT   26   52000           3     4.0
4  105  Binod         HR   31   58000           6     3.2
5  106  Kiran    Finance   40   90000          15     4.5
6  107  Nisha         IT   23   48000           1     3.9
7  108  Sunil    Finance   38   85000          12     4.1

In [16]:
# replace value IT - Tech, HR - Human Resource
df3['department'] = df3['department'].replace({"IT": "Tech", "HR":"Human Resource"})