In [45]:
import pandas as pd

In [46]:
df = pd.read_csv("raw_data.csv")
# apply
df["tax"] = df["income"].apply(lambda x: "20%" if x >= 50000 else "10%")

In [47]:
# map
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"}
df["gender"] = df["gender"].map(gender_map)
df

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [48]:
# assign
df = df.assign(new_salary = df["income"] * 1.5)
df

    id          name   age country gender   income  tax  new_salary
0    1      John Doe  29.0     USA      M  55000.0  20%     82500.0
1    1      John Doe  29.0     USA      M  55000.0  20%     82500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     93000.0
3    3          Alex   NaN     USA      U  47000.0  10%     70500.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     76500.0
6    6           NaN  45.0   India      F  73000.0  20%    109500.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%    102000.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     93000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     67500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     87000.0

In [51]:
# replace
df["country"] = df["country"].replace("USA", "US")
df

    id          name   age country gender   income  tax  new_salary
0    1      John Doe  29.0      US      M  55000.0  20%     82500.0
1    1      John Doe  29.0      US      M  55000.0  20%     82500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     93000.0
3    3          Alex   NaN      US      U  47000.0  10%     70500.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     76500.0
6    6           NaN  45.0   India      F  73000.0  20%    109500.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%    102000.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     93000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     67500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%     87000.0