In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("raw_data.csv")

# groupby country and find mean of salary
df.groupby("country")["income"].mean()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64

In [10]:
# groupby country and find minimum salary
df.groupby("country")["income"].min()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       47000.0
Name: income, dtype: float64

In [11]:
# groupby country and find minimum salary
df.groupby("country")["income"].max()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [14]:
# multiple aggregate
df.groupby("country")["income"].agg(["mean", "min", "max"])

            mean      min      max
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  47000.0  62000.0

In [16]:
# mulitple aggregate renaming the column name
df.groupby("country")['income'].agg(avg_salary="mean", min_salary="min")

         avg_salary  min_salary
country
Canada      62000.0     62000.0
China       51000.0     51000.0
India       73000.0     73000.0
Mexico      45000.0     45000.0
Spain           NaN         NaN
USA         55400.0     47000.0

In [19]:
# multiple aggregate with different operation in different column
df.groupby("country").agg(
    avg_salary=("income","mean"),
    min_salary=("income", "min")
)

         avg_salary  min_salary
country
Canada      62000.0     62000.0
China       51000.0     51000.0
India       73000.0     73000.0
Mexico      45000.0     45000.0
Spain           NaN         NaN
USA         55400.0     47000.0